name: Build and Release with Nix

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Build application
      run: nix bundle . -o lectic

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lectic
        path: ./lectic

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: lectic

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./lectic
        asset_name: lectic
        asset_content_type: application/octet-stream
